source 'http://rubygems.org'

gem 'rails', '3.1.0.rc1'
gem 'sqlite3'

gem 'zfben_rails_rake'
gem 'zfben_rails_assets'


# Added by zfben_rails_assets

# html
gem 'haml'
gem 'haml-coderay'
gem 'coderay_bash'

# css
gem 'sass-rails', :git => 'git://github.com/rails/sass-rails.git'
gem 'compass', :git => 'https://github.com/chriseppstein/compass.git', :branch => 'rails31'

# js
gem 'therubyracer'
gem 'coffee-script'
gem 'uglifier'

# End zfben_rails_assets