# html
gem 'haml'
gem 'haml-coderay'
gem 'coderay_bash'

# css
gem 'sass-rails', :git => 'https://github.com/rails/sass-rails.git'
gem 'compass', :git => 'https://github.com/chriseppstein/compass.git', :branch => 'rails31'

# js
gem 'therubyracer'
gem 'coffee-script'
gem 'uglifier'
